"""create vehicles table

Revision ID: 70ffbecfd3cf
Revises: 2f0621d87624
Create Date: 2026-03-15 11:34:37.441471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ffbecfd3cf'
down_revision: Union[str, Sequence[str], None] = '2f0621d87624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('TRUCK', 'VAN', 'SEMI', 'REFRIGERATED', name='vehicletype'), nullable=False),
    sa.Column('max_load_kg', sa.Float(), nullable=True),
    sa.Column('max_load_volume_m3', sa.Float(), nullable=True),
    sa.Column('fuel_consumption_per_100km', sa.Float(), nullable=True),
    sa.Column('last_service_date', sa.String(length=20), nullable=True),
    sa.Column('next_service_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'SERVICE', 'INACTIVE', name='vehiclestatus'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
