"""create schedules and conflicts tables

Revision ID: f5f2d7a77cc4
Revises: 35f93bd611b7
Create Date: 2026-03-15 12:21:56.910416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f2d7a77cc4'
down_revision: Union[str, Sequence[str], None] = '35f93bd611b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('conflict_type', sa.Enum('DRIVER_OVERLAP', 'VEHICLE_OVERLAP', 'MAX_HOURS_EXCEEDED', 'MISSING_BREAK', 'REST_VIOLATION', 'LICENSE_EXPIRED', name='conflicttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'IGNORED', name='conflictstatus'), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_start', sa.String(length=5), nullable=False),
    sa.Column('shift_end', sa.String(length=5), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', 'CUSTOM', name='shifttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('day_off_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
